[theme]
theme = "bad-wolf"

[icons]
icons="awesome6"
[icons.overrides]
music = "\uf144"

[[block]]
block = "memory"
format = "$icon $mem_used/$mem_total"

[[block]]
block = "sound"
max_vol = 130

[[block]]
block = "music"
format = "{$combo.str(max_w:20,rot_interval:0.2) $prev $play $next|}"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R')"
[[block.click]]
button = "left"
cmd = "gsimplecal"

[[block]]
block = "temperature"
format = " $icon $average"
interval = 5

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "$icon $percentage"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
[[block.click]]
button = "left"
cmd = "systemctl printf 'suspend\npoweroff\nreboot' | rofi -dmenu "
